//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MobileTariffs {
    
    private MobileTariffsTariff[] tariffField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tariff")]
    public MobileTariffsTariff[] Tariff {
        get {
            return this.tariffField;
        }
        set {
            this.tariffField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MobileTariffsTariff {
    
    private string nameField;
    
    private string operatorNameField;
    
    private string payrollField;
    
    private MobileTariffsTariffСallPrices сallPricesField;
    
    private string sMSPriceField;
    
    private MobileTariffsTariffParameters parametersField;
    
    private string nameField1;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string OperatorName {
        get {
            return this.operatorNameField;
        }
        set {
            this.operatorNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Payroll {
        get {
            return this.payrollField;
        }
        set {
            this.payrollField = value;
        }
    }
    
    /// <remarks/>
    public MobileTariffsTariffСallPrices СallPrices {
        get {
            return this.сallPricesField;
        }
        set {
            this.сallPricesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SMSPrice {
        get {
            return this.sMSPriceField;
        }
        set {
            this.sMSPriceField = value;
        }
    }
    
    /// <remarks/>
    public MobileTariffsTariffParameters Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField1;
        }
        set {
            this.nameField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MobileTariffsTariffСallPrices {
    
    private string innerCallsField;
    
    private string outerCallsField;
    
    private string landlineCallsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string InnerCalls {
        get {
            return this.innerCallsField;
        }
        set {
            this.innerCallsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OuterCalls {
        get {
            return this.outerCallsField;
        }
        set {
            this.outerCallsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string LandlineCalls {
        get {
            return this.landlineCallsField;
        }
        set {
            this.landlineCallsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MobileTariffsTariffParameters {
    
    private string countFavoriteNumbersField;
    
    private MobileTariffsTariffParametersTimeTariffing timeTariffingField;
    
    private string connectionFeeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string CountFavoriteNumbers {
        get {
            return this.countFavoriteNumbersField;
        }
        set {
            this.countFavoriteNumbersField = value;
        }
    }
    
    /// <remarks/>
    public MobileTariffsTariffParametersTimeTariffing TimeTariffing {
        get {
            return this.timeTariffingField;
        }
        set {
            this.timeTariffingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ConnectionFee {
        get {
            return this.connectionFeeField;
        }
        set {
            this.connectionFeeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum MobileTariffsTariffParametersTimeTariffing {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12Seconds")]
    Item12Seconds,
    
    /// <remarks/>
    Minute,
}
